<!DOCTYPE library [
<!ELEMENT library (books,members)>
<!ELEMENT books (book1,book2)>
<!ELEMENT book1 (title,author,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT book2 (title,author,price)> 
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT members (member1,member2)>
<!ELEMENT member1 (name,address,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT member2 (name,address,phone)> 
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST book1 bookId CDATA #REQUIRED>
<!ATTLIST book2 bookId CDATA #REQUIRED>
<!ATTLIST member1 memberId CDATA #REQUIRED>
<!ATTLIST member2 memberId CDATA #REQUIRED>
]>
<library>
<books>
<book1 bookId="1">
<title>Web Designing and Publishing</title> 
<author>Tyson</author>
<price>333</price>
</book1>
<book2 bookId="2">
<title>Artificial Intelligence</title>
<author>SAI SNEHA</author>
<price>500</price>
</book2>
</books>
<members>
<member1 memberId="101">
<name>M sharada</name>
<address>Ramagiri</address>
<phone>9177354706</phone>
</member1>
<member2 memberId="102">
<name>M surya sekhar</name>
<address>Delhi</address>
<phone>8919194504</phone>
</member2>
</members>
</library>